[{"bug_type":"QUANDARY_TAINT_ERROR","qualifier":"Other(taint()) at line 17, column 17 ~> Other(sink()) at line 22, column 2.","severity":"ERROR","line":22,"column":2,"procedure":"main","procedure_start_line":14,"file":"TestPrograms/python-ctools-demo/temp_run.cpp","bug_trace":[{"level":0,"filename":"TestPrograms/python-ctools-demo/temp_run.cpp","line_number":17,"column_number":17,"description":"Return from taint"},{"level":0,"filename":"TestPrograms/python-ctools-demo/temp_run.cpp","line_number":22,"column_number":2,"description":"Call to sink with tainted index 0"}],"key":"temp_run.cpp|main|QUANDARY_TAINT_ERROR","hash":"a4f435efa367ad28ce044151cefb6d1f","bug_type_hum":"Taint Error"}]
